CREATE TABLE "Full_data" (
    "Entry_ID" float(50),
    "Age" float (3) not null, 
    "Hours_per_day" float(50) not null,
    "While_working" varchar(3) not null, 
    "Instrumentalist" varchar(3) not null,
    "Composer" varchar(3) not null, 
    "Fav_genre" varchar(50) not null,
    "Exploratory" varchar(3) not null, 
    "Foreign_languages" varchar(3) not null, 
    "BPM" float(50) not null, 
    "Classical" varchar(50) not null, 
    "Country" varchar(50) not null,
    "EDM" varchar(50) not null, 
    "Folk" varchar(50) not null, 
    "Gospel" varchar(50) not null, 
    "Hip_hop" varchar(50) not null, 
    "Jazz" varchar(50) not null,
    "K_pop" varchar(50) not null, 
    "Latin" varchar(50) not null, 
    "Lofi" varchar(50) not null,
    "Metal" varchar(50) not null, 
    "Pop" varchar(50) not null, 
    "R&B" varchar(50) not null, 
    "Rap" varchar(50) not null, 
    "Rock" varchar(50) not null, 
    "Video_game_music" varchar(50) not null, 
    "Anxiety" float(50) not null,
    "Depression" float(50) not null, 
    "Insomnia" float(50) not null, 
    "OCD" float(50) not null, 
    "Music_effects" varchar(50) not null,
    CONSTRAINT "Full_data" PRIMARY KEY ("Entry_ID")
      
);